sudo: required

language: python
python: 2.7

services:
  - docker

env:
  - TOX_ENV=py27
  - COMPOSE=True

git:
  submodules: false

before_install:
  - docker pull manabuishii/docker-sge-client:0.1.0
  - docker pull manabuishii/docker-sge-master:0.1.0
